//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMessages()
        {
            this.tblMessagesSend = new HashSet<tblMessagesSend>();
        }
    
        public int MessageID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ToNumber { get; set; }
        public string Message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMessagesSend> tblMessagesSend { get; set; }
    }
}
