//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessagesSend
    {
        public int MessageSendID { get; set; }
        public int MessageID { get; set; }
        public System.DateTime DateSent { get; set; }
        public string ConfirmatedCode { get; set; }
        public string ResponseJSON { get; set; }
    
        public virtual tblMessages tblMessages { get; set; }
    }
}
